blog/blog/urls.py
from contacts.sitemaps import ContactSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from homepage.sitemaps import MainSitemap
from posts.sitemaps import GroupSitemap, PostSitemap, ProfileSitemap
from posts.views import generate_news_sitemap

sitemaps = {
    "main": MainSitemap,
    "posts": PostSitemap,
    "group": GroupSitemap,
    "profiles": ProfileSitemap,
    "contacts": ContactSitemap,
}

urlpatterns = [
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admindd/", admin.site.urls),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("search", include("search.urls", namespace="search")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("sitemap-news.xml", generate_news_sitemap, name="news_sitemap"),
    path("cookies/", include("cookie_consent.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

admin.site.site_header = "Wobidobi - Admin Panel"
admin.site.site_title = "Wobidobi"
admin.site.index_title = "Welcome to the Admin Interface!"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

blog/search/urls.py
from django.urls import path

from . import views

app_name = "search"


urlpatterns = [
    path("", views.search_view, name="search"),
]

blog/templates/base.html
{% load static %}
{% load capture_tags %}
{% load cookie_consent_tags %}
<!DOCTYPE html>
<html lang="en" data-wf-page="{% block wf_page_id %}66347d9e6fab56ada53cc375{% endblock wf_page_id %}" data-wf-site="66347d9e6fab56ada53cc317">
<head>
  {% comment %} Cookies scripts {% endcomment %}
  {% include 'cookie_consent/base/header.html' %}

  {% if request|cookie_group_accepted:"statistic" %}
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-TGWM24RW');</script>
    <!-- End Google Tag Manager -->
  {% endif %}

  <meta charset="utf-8">
  <title>{% capture as meta_title %}{% block title %}Wobidobi - The Social Media You'll Ever Need{% endblock %}{% endcapture %}</title>
  <meta name="description" content="{% capture as meta_description %}{% block description %}Discover a variety of informative and engaging content on Wobidobi.com. Stay updated with the latest trends and stories from around the world!{% endblock %}{% endcapture %}">

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@wobidobi" />
  <meta name="twitter:title" content="{{ meta_title|truncatechars:50 }}" />
  <meta name="twitter:description" content="{{ meta_description|truncatechars:120 }}" />

  <meta property="og:title" content="{{ meta_title|truncatechars:50 }}"/>
  <meta property="og:description" content="{{ meta_description|truncatechars:65 }}"/>
  <meta property="og:type" content="website" />
  <meta property="og:image" content="{% block og_image %}{% static 'images/preview.webp' %}{% endblock %}"/>
  <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}" />
  <meta name="mailru-domain" content="r5uigAzQsjj2dKAt" />
  <link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}" />
  <meta content="width=device-width, initial-scale=1" name="viewport">
  
  <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/components.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/blog-template-796040.css' %}" rel="stylesheet" type="text/css">

  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous">
  
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({  google: {    families: ["Manrope:regular,600,700"]  }});</script>
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>

  <link href="{% static 'images/favicon.svg' %}" rel="shortcut icon" type="image/x-icon">
  <link href="{% static 'images/webclip.svg' %}" rel="apple-touch-icon">
  <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "url": "https://wobidobi.com/",
        "potentialAction": {
          "@type": "SearchAction",
          "target": "{{ request.scheme }}://{{ request.get_host }}{% url 'search:search' %}?&q={search_term_string}",
          "query-input": "required name=search_term_string"
        }
    }
  </script>
  {% if request|cookie_group_accepted:"marketing" %}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7665246149065553" crossorigin="anonymous"></script>
  {% endif %}
  {% block before_close_head %}{% endblock %}
</head>
<body>
  {% if request|cookie_group_accepted:"statistic" %}
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TGWM24RW"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
  {% endif %}
  <div class="page-wrapper">
    {% include 'includes/nav/nav.html' %}
    {% block content %}
      <!-- Page Body -->
    {% endblock %}
    {% include 'includes/footer/footer.html' %}
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=66347d9e6fab56ada53cc317" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  {% comment %} {% compress js file base %} {% endcomment %}
  <script src="{% static 'js/blog-template-796040.js' %}" type="text/javascript"></script>
  {% comment %} {% endcompress %} {% endcomment %}

  {% comment %} Cookies template {% endcomment %}
  {% include 'cookie_consent/base/body.html' %}

  {% block before_close_body %}{% endblock %}
</body>
</html>