blog/blog/urls.py
from contacts.sitemaps import ContactSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from homepage.sitemaps import MainSitemap
from posts.sitemaps import GroupSitemap, PostSitemap, ProfileSitemap
from posts.views import generate_news_sitemap

sitemaps = {
    "main": MainSitemap,
    "posts": PostSitemap,
    "group": GroupSitemap,
    "profiles": ProfileSitemap,
    "contacts": ContactSitemap,
}

urlpatterns = [
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admindd/", admin.site.urls),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("search", include("search.urls", namespace="search")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("sitemap-news.xml", generate_news_sitemap, name="news_sitemap"),
    path("cookies/", include("cookie_consent.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

admin.site.site_header = "Wobidobi - Admin Panel"
admin.site.site_title = "Wobidobi"
admin.site.index_title = "Welcome to the Admin Interface!"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

blog/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("run-task/", views.run_task_now, name="run_task_now"),
    path('unlock/', views.unlock_tasks, name='unlock_tasks'),
    path("create/", views.post_create, name="create"),
    path("follow/", views.follow_index, name="follow_index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("profile/<username>/", views.profile, name="profile"),
    path("<str:slug>/", views.post_detail, name="post_detail"),
    path("<str:slug>/edit/", views.post_edit, name="edit"),
    # path("<str:slug>/comment/", views.add_comment, name="add_comment"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

blog/posts/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
# from html_sanitizer.django import get_sanitizer

from .models import Comment, Post

# sanitizer = get_sanitizer(name="post_form_inputs")


class CourseFormCKEditorWidget(CKEditorWidget):
    template_name = "custom_ckeditor/widget.html"


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        # Clean label='' for all fields
        for field_name, field in self.fields.items():
            if field_name != "published":
                field.label = ""
        if "cached_filename" in self.initial:
            self.fields["image"].widget.attrs["data-cached-filename"] = self.initial[
                "cached_filename"
            ]

    # def clean_text(self):
    #     value = self.cleaned_data.get("text")
    #     return sanitizer.sanitize(value)

    class Meta:
        model = Post
        fields = "__all__"
        exclude = ["author", "feature", "pub_date", "paid", "published"]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "input w-input",
                    "maxlength": "100",
                    "placeholder": "Title",
                    "label": "",
                }
            ),
            "slug": forms.TextInput(
                attrs={
                    "class": "input w-input",
                    "maxlength": "50",
                    "placeholder": "Slug",
                }
            ),
            "short_text": forms.TextInput(
                attrs={
                    "class": "input w-input",
                    "maxlength": "250",
                    "placeholder": "Short description",
                }
            ),
            "text": CourseFormCKEditorWidget(
                config_name="cke_post_form_inputs",
                attrs={
                    "class": "input w-input",
                    "maxlength": "4000",
                    "placeholder": "Body",
                },
            ),
            "group": forms.Select(
                attrs={
                    "class": "w-commerce-commercecheckoutshippingcountryselector input medium last",
                }
            ),
            "image": forms.ClearableFileInput(
                attrs={
                    "class": "custom-image-upload-class",
                    "accept": "image/*",
                }
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)
        labels = {"text": "Comment title"}
        help_text = {"text": "Comment"}

        # widgets = {
        #     "name": forms.TextInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "maxlength": "200",
        #             "placeholder": "Жесткий свет",
        #             "data-count": "100",
        #         }
        #     ),
        #     "slug": forms.TextInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "maxlength": "50",
        #             "placeholder": "zhestkij-svet",
        #         }
        #     ),
        #     "description": CourseFormCKEditorWidget(
        #         config_name="cke_front_course_form_inputs",
        #         attrs={
        #             "class": "form_textarea w-input",
        #         },
        #     ),
        #     "image": forms.ClearableFileInput(
        #         attrs={
        #             "class": "custom-image-upload-class",
        #             "accept": "image/*",
        #         }
        #     ),
        #     "link": forms.TextInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "maxlength": "256",
        #             "placeholder": "https://vebinaroom.ru/",
        #         }
        #     ),
        #     "start_date": forms.TextInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "placeholder": "Дата начала обучения",
        #             "id": "datepicker",
        #         }
        #     ),
        #     "classes_count": forms.NumberInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "max": "999999999",
        #         }
        #     ),
        #     "length": forms.NumberInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "max": "999999999",
        #         }
        #     ),
        #     "length_metric": forms.Select(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "certificate": forms.CheckboxInput(
        #         attrs={
        #             "data-name": "certificate",
        #             "style": "opacity:0;position:absolute;z-index:-1",
        #         }
        #     ),
        #     "free": forms.CheckboxInput(
        #         attrs={
        #             "data-name": "free",
        #             "style": "opacity:0;position:absolute;z-index:-1",
        #         }
        #     ),
        #     "request_price": forms.CheckboxInput(
        #         attrs={
        #             "data-name": "request_price",
        #             "style": "opacity:0;position:absolute;z-index:-1",
        #         }
        #     ),
        #     "price": forms.NumberInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "max": "999999999",
        #         }
        #     ),
        #     "price_per_month": forms.NumberInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "max": "999999999",
        #         }
        #     ),
        #     "price_new": forms.NumberInput(
        #         attrs={
        #             "class": "form_input w-input",
        #             "max": "999999999",
        #         }
        #     ),
        #     "group": forms.Select(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "topic": forms.SelectMultiple(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "language": forms.SelectMultiple(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "level": forms.Select(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "school": forms.Select(
        #         attrs={
        #             "class": "form_selector w-select",
        #         }
        #     ),
        #     "tag_group_author": forms.CheckboxInput(
        #         attrs={
        #             "data-name": "visible",
        #             "style": "opacity:0;position:absolute;z-index:-1",
        #         }
        #     ),
        #     "visible": forms.CheckboxInput(
        #         attrs={
        #             "data-name": "visible",
        #             "style": "opacity:0;position:absolute;z-index:-1",
        #         }
        #     ),
        # }

blog/posts/views.py
import logging

from celery_singleton import clear_locks
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone

from blog.celery import app as celery_app

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .tasks import fetch_and_create_post
from .utils import insert_advertisement

logger = logging.getLogger("posts")


def index(request):
    post_list = Post.objects.select_related("group").all()
    paginator = Paginator(post_list, settings.POSTS_FOR_PAGINATION)
    page_number = request.GET.get("page")
    posts = paginator.get_page(page_number)
    context = {
        "posts": posts,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.POSTS_FOR_PAGINATION)
    page_number = request.GET.get("page")
    posts = paginator.get_page(page_number)
    context = {
        "group": group,
        "posts": posts,
    }
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all().order_by("-pub_date")
    paginator = Paginator(post_list, settings.POSTS_FOR_PAGINATION)
    page_number = request.GET.get("page")
    posts = paginator.get_page(page_number)
    if request.user.is_authenticated:
        following = author.following.filter(user=request.user).exists()
    else:
        following = False
    context = {"author": author, "posts": posts, "following": following}
    return render(request, "posts/profile.html", context)


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST or None)
    related_posts = (
        Post.objects.filter(group=post.group)
        .select_related("group", "author__user_profile")
        .exclude(slug=slug)
        .order_by("-pub_date")[3:6]
    )
    comments = post.comments.all()
    sd = post.sd
    absolute_url = request.build_absolute_uri(
        reverse("posts:post_detail", args=[post.slug])
    )
    sd["mainEntityOfPage"] = absolute_url
    sd["url"] = absolute_url
    post.text = insert_advertisement(post.text, template="ads/post_detail.html")
    context = {
        "post": post,
        "form": form,
        "comments": comments,
        "related_posts": related_posts,
        "sd": sd,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, "posts/create_post.html", {"form": form})
    instance = form.save(commit=False)
    instance.author = request.user
    instance.save()
    return redirect("posts:profile", instance.author)


@login_required
def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.author == request.user:
        form = PostForm(
            request.POST or None, files=request.FILES or None, instance=post
        )
        if not form.is_valid():
            context = {
                "form": form,
                "post": post,
                "is_edit": True,
            }
            return render(request, "posts/create_post.html", context)
        form.save()
    return redirect("posts:post_detail", slug)


@login_required
def add_comment(request, slug):
    post = get_object_or_404(Post, slug)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", slug=slug)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.POSTS_FOR_PAGINATION)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    following_author = get_object_or_404(User, username=username)
    if request.user == following_author:
        return redirect("posts:profile", username=username)
    Follow.objects.get_or_create(user=request.user, author=following_author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    followed_author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=followed_author).delete()
    return redirect("posts:profile", username=username)


def run_task_now(request):
    logger.debug("run_task_now view called")
    fetch_and_create_post.delay()
    logger.debug("Task fetch_and_create_post.delay() called")
    return JsonResponse({"status": "Task is running"})


def unlock_tasks(request):
    clear_locks(celery_app)
    return JsonResponse({"status": "All tasks unlocked"})


def generate_news_sitemap(request):
    recent_posts = Post.objects.filter(
        pub_date__gte=timezone.now() - timezone.timedelta(days=2)
    )
    posts_with_full_urls = [
        {
            "url": request.build_absolute_uri(post.get_absolute_url()),
            "pub_date": post.pub_date.strftime("%Y-%m-%d"),
            "title": post.title,
            "author_name": post.author.get_full_name(),
        }
        for post in recent_posts
    ]

    xml_content = render_to_string(
        "posts/sitemap/news_template.xml", {"posts": posts_with_full_urls}
    )
    return HttpResponse(xml_content, content_type="application/xml")

blog/templates/posts/create_post.html
{% extends "base.html" %}
{% load static %} 
{% block wf_page_id %}66347d9e6fab56ada53cc419{% endblock wf_page_id %}

{% load user_filters %}

{% block title %}
  {% if is_edit %} Edit article {% else %} Create article {% endif %}
{% endblock %} 

{% block before_close_head %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block content %}
<div class="w-users-userformpagewrap page-wrapper-utility-pages wide">
  <div data-w-id="62b0cb992aca6122cbb3a86300000000000b" style="-webkit-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0" class="w-users-usersignupformwrapper card form utility-pages">
    <div class="w-users-userformheader">
      <h1 class="heading-h2-size">{% if is_edit %} Edit article {% else %} Create article {% endif %}</h1>
      <p>{% if is_edit %}Refine your thoughts and update your article here.{% else %}Begin shaping your thoughts into an article today.{% endif %}</p>
    </div>
    <form method="post" action="
        {% if is_edit %}
            {% url 'posts:edit' post.slug %}
        {% else %}
            {% url 'posts:create' %}
        {% endif %} 
        " enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }}
      <button type="submit" class="w-users-userformbutton btn-primary w-button">{% if is_edit %} Edit {% else %} Create {% endif %}</button>
    </form>
  </div>
</div>
{% endblock %}

{% block before_close_body %}
  <link href="{% static 'css/form-helptext.css' %}" rel="stylesheet" type="text/css">
  <script  src="{% static 'js/form/image.js' %}"></script>
  <script>
    $(document).ready(function () {
      $(".django-ckeditor-widget").css("width", "100%")
  });
  </script>
{% endblock %}

blog/templates/posts/follow.html
{% extends "base.html" %}

{% block title %}Follow{% endblock %}
{% block header %}Follow{% endblock %}
{% block content %}
{% load thumbnail %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <h3>
        Автор:
            <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.username }}</a>, 
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.group%}   
        все записи группы: <a href="{% url 'posts:group' post.group.slug %}">"{{ post.group.title }}"</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %} 
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

blog/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block wf_page_id %}66347d9e6fab56ada53cc3ce{% endblock wf_page_id %}

{% load render_json_ld from json_ld %}

{% block title %}{{ post.title |add:" - Wobidobi.com" | truncatechars:50}}{% endblock %}
{% block description %}{{ post.short_text|truncatechars:120 }}{% endblock %}
{% block og_image %}{% thumbnail post.image "1024" crop="center" upscale=True as im %}{{ im.url }}{% endthumbnail %}{% endblock %}


{% block before_close_head %}
{% render_json_ld sd %}
{% endblock %}


{% block content %}

{% thumbnail post.image "1024" crop="center" upscale=True as im %}
<div class="section blog-post-hero" style="background-image:url('{{ im.url }}')">
  <div class="container-default blog-post w-container">
    <div data-w-id="66239862-f976-9aa5-4692-104b01ddc9f7" style="-webkit-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0" class="inner-container _740px">
      <div>
        <div class="blog-card-bg-badge-wrapper">
          <a href="{% url 'posts:group' post.group.slug %}" class="badge-primary bold white link">{{ post.group }}</a>
          {% if request.user.is_authenticated and request.user == post.author %}
            <a href="{% url 'posts:edit' post.slug %}" class="badge-primary bold small white link">Edit</a>
          {% endif %}
        </div>
        <h1 class="display-1 color-neutral-100 mg-bottom-32px">{{post.title}}</h1>
        <div class="blog-card-details-container">
          <div class="author-container">
            <div class="avatar-circle _01 blog-card-bg-author-image">
              {% thumbnail post.author.user_profile.image "50x50" crop="center" upscale=True as im %}
                <div class="avatar-circle _01 blog-card-bg-author-image">
                    <img src="{{ im.url }}" alt="{{post.author.first_name}} {{post.author.last_name}}" loading="lazy">
                </div>
              {% endthumbnail %}
            </div>
            <a href="{% url 'posts:profile' post.author.username%}" target="_blank" rel="noopener noreferrer">
            <div class="text-200 bold color-neutral-100">{{post.author.first_name}} {{post.author.last_name}}</div>
            </a>
          </div>
          <div class="blog-card-bg-date-container">
            <div class="line-rounded-icon clock-icon"></div>
            <div class="text-200 bold color-neutral-100">{{post.pub_date|date:"F j, Y" }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-overlay-gradient blog-post"></div>
</div>
{% endthumbnail %}

<div class="section main-posts post">
  <div class="container-default w-container">
    <div class="w-layout-grid grid-2-columns sidebar-content left">
      {% include "includes/sidebar.html" %}
      <div id="w-node-bbe442ff-821e-d89f-b98f-f15bad946368-a53cc3ce">
        <div data-w-id="74944fe2-2ca0-2d4f-bf34-7f2c1b19df89" style="opacity:0" class="rich-text w-richtext">
          {{ post.text|safe}}
        </div>
        <div class="divider mg-bottom-48px"></div>
        {% if social %}
          <div class="flex-horizontal space-between">
            <div class="text-200 bold color-neutral-800">Share with your friends</div>
            <div class="w-layout-grid social-media-grid-top right">
              {% include "includes/social_links.html" with type="share" social=social %}
            </div>
          </div>
        {% endif %}
      </div>
    </div>
    <div></div>
  </div>
</div>

<div class="section">
  <div class="container-default w-container">
    <div data-w-id="60bc858c-be07-823b-c8c8-acf93dd62984" style="-webkit-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0" class="w-layout-grid grid-2-columns title-and-categories">
      <h2 class="mg-bottom-0">Related articles</h2>
      {% if post.group.slug %}
        <a id="w-node-_2802096f-6bb2-9026-954c-4585aa70a9c8-a53cc3ce" href="{% url 'posts:group' post.group.slug %}" class="btn-primary w-button">Browse all articles</a>
      {% endif %}
    </div>
    <div class="w-dyn-list">
      <div data-w-id="7c82d348-f271-5012-e28e-daf6f5a2817d" style="-webkit-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-moz-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);-ms-transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);transform:translate3d(0, 10%, 0) scale3d(1, 1, 1) rotateX(0) rotateY(0) rotateZ(0) skew(0, 0);opacity:0" role="list" class="grid-3-columns w-dyn-items">
        {% for post in related_posts %}
        <div role="listitem" class="w-dyn-item">
          <a data-w-id="7c82d348-f271-5012-e28e-daf6f5a2817f" href="{% url 'posts:post_detail' post.slug%}" class="blog-card-bg sidebar w-inline-block">
            <div class="blog-card-bg-container small">
              <div class="text-uppercase mg-bottom-16px">
                <div class="text-200 bold color-neutral-100">{{post.group}}</div>
              </div>
              <h3 class="heading-h4-size color-neutral-100 mg-bottom-0">{{post.title}}</h3>
            </div>
            <div class="bg-overlay-gradient blog-card-bg-overlay"></div>
            {% thumbnail post.image "314x314" crop="center" upscale=True as im %}
              <img src="{{ im.url }}" alt="{{post.title}}" class="blog-card-bg-image">
            {% endthumbnail %}
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{"Profile " | add:author.get_full_name |add:" - Wobidobi.com" | truncatechars:50}}{% endblock %}
{% block description %}Explore personal profiles, connect with friends, and share your own stories on Wobidobi.com. Dive into a world of engaging content and social interaction!{% endblock %}

{% block content %}

<div class="section main-posts categories">
  <div class="container-default w-container">
      <div class="w-layout-grid grid-2-columns sidebar-content">
          <div id="w-node-_504883fc-b26e-b64f-cfed-179d1ea0a43c-a53cc375">
            <div class="header-col-2">
              <div data-w-id="15ed5577-8de7-6600-70d7-d1be22af3790" style="opacity: 1;" class="_2-heading-wrapper no-mb">
                  <h1 id="w-node-_699558eb-a04b-13e4-9899-aa385ada716d-1e6b134d" class="heading-h2-size mg-left-6px">{{author.first_name}} {{author.last_name}}</h1>
                  <div class="heading-h2-size">articles: {{ posts.paginator.count }}</div>
              </div>
              {% if request.user.is_authenticated and request.user != author %}
                {% if following %}
                  <a class="btn-primary small white w-button" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                    Unsubscribe
                  </a>
                {% else %}
                  <a class="btn-primary small w-button" href="{% url 'posts:profile_follow' author.username %}" role="button">
                    Subscribe
                  </a>
                {% endif %}
              {% endif %}
              </div>
              <div data-w-id="18179618-f4f1-bf64-3fac-c197bb5b10d6" style="opacity:0" class="w-dyn-list">
                  <div role="list" class="grid-1-column gap-row-48px w-dyn-items">
                      {% for post in posts %}
                      <div role="listitem" class="w-dyn-item">
                          <a href="{% url 'posts:post_detail' post.slug %}" class="blog-card-featured-wrapper w-inline-block">
                              <div data-w-id="18179618-f4f1-bf64-3fac-c197bb5b10da" class="w-layout-grid grid-2-columns blog-card-primary">
                                  {% thumbnail post.image "314x314" crop="center" upscale=True as im %}
                                  <div class="blog-card-image-wrapper featured-v1">
                                      <img src="{{ im.url }}" alt="{{post.title}}" class="blog-card-image featured-v1">
                                  </div>
                                  {% endthumbnail %}
                                  <div class="blog-card-content-default">
                                        <div class="header-col-2">
                                            <div data-w-id="15ed5577-8de7-6600-70d7-d1be22af3790" style="opacity: 1;" class="_2-heading-wrapper no-mb">
                                                <div class="text-uppercase mg-bottom-16px">
                                                    <div class="text-200 bold">{{post.group}}</div>
                                                </div>
                                            </div>
                                            {% if request.user.is_authenticated and request.user == post.author %}
                                                <a class="btn-primary small link" href="{% url 'posts:edit' post.slug %}" role="button">Edit</a>
                                            {% endif %}
                                        </div>
                                      <h3>{{post.title}}</h3>
                                      <p class="mg-bottom-24px">{{post.short_text}}</p>
                                      <div class="blog-card-details-container">
                                          <div class="author-container">
                                              {% thumbnail post.author.user_profile.image "50x50" crop="center" upscale=True as im %}
                                              <div class="avatar-circle _01 blog-card-bg-author-image">
                                                  <img src="{{ im.url }}" loading="lazy" alt="{{ author.get_full_name }}">
                                              </div>
                                              {% endthumbnail %}
                                              <div class="text-100 bold color-neutral-800">{{ author.get_full_name }}</div>
                                          </div>
                                          <div class="blog-card-bg-date-container">
                                              <div class="line-rounded-icon clock-icon dark"></div>
                                              <div class="text-100 bold color-neutral-800">{{post.pub_date|date:"F j, Y" }}</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      </div>
                      {% endfor %}
                      {% include 'posts/includes/paginator.html' %}
                  </div>
              </div>
          </div>
          {% include "includes/sidebar.html" %}
      </div>
  </div>
</div>
{% endblock %}