blog/blog/urls.py
from contacts.sitemaps import ContactSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from homepage.sitemaps import MainSitemap
from posts.sitemaps import GroupSitemap, PostSitemap, ProfileSitemap
from posts.views import generate_news_sitemap

sitemaps = {
    "main": MainSitemap,
    "posts": PostSitemap,
    "group": GroupSitemap,
    "profiles": ProfileSitemap,
    "contacts": ContactSitemap,
}

urlpatterns = [
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admindd/", admin.site.urls),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("search", include("search.urls", namespace="search")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("sitemap-news.xml", generate_news_sitemap, name="news_sitemap"),
    path("cookies/", include("cookie_consent.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

admin.site.site_header = "Wobidobi - Admin Panel"
admin.site.site_title = "Wobidobi"
admin.site.index_title = "Welcome to the Admin Interface!"


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

blog/contacts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.ContactViews.as_view(), name="contact"),
    path("thank-you/", TemplateView.as_view(template_name="contacts/thank_you.html")),
]

blog/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("run-task/", views.run_task_now, name="run_task_now"),
    path('unlock/', views.unlock_tasks, name='unlock_tasks'),
    path("create/", views.post_create, name="create"),
    path("follow/", views.follow_index, name="follow_index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("profile/<username>/", views.profile, name="profile"),
    path("<str:slug>/", views.post_detail, name="post_detail"),
    path("<str:slug>/edit/", views.post_edit, name="edit"),
    # path("<str:slug>/comment/", views.add_comment, name="add_comment"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

blog/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views
from .forms import (
    AccountLoginForm,
    AccountPasswordChangeForm,
    AccountPasswordResetConfirmForm,
    AccountPasswordResetForm,
)

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("signup-done/", views.SignUpDone.as_view(), name="signup_done"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=AccountLoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            form_class=AccountPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            form_class=AccountPasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html",
            form_class=AccountPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
]

blog/templates/includes/nav/nav.html
{% load static %}
<div data-animation="default" data-collapse="small" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="header-wrapper w-nav">
  <div class="container-default w-container">
    <div class="header-content-wrapper">
      <div class="header-top-wrapper">
        <div class="header-middle social-media">
          <div>
            <div class="w-layout-grid social-media-grid-top header">
              {% include "includes/social_links.html" with type="profile" social=social %}
            </div>
          </div>
        </div>
        <a href="/" aria-current="page" class="header-logo-link w-nav-brand w--current">
          <img src="{% static 'images/logo.svg' %}" alt="Wobidobi - Logo" class="header-logo">
        </a>
        <div class="header-right-side search">
          <div data-node-type="commerce-cart-wrapper" data-open-product="" data-wf-cart-type="modal" data-wf-cart-query="" data-wf-page-link-href-prefix="" class="w-commerce-commercecartwrapper">
            {% comment %} <a href="#" data-node-type="commerce-cart-open-link" class="w-commerce-commercecartopenlink cart-wrapper w-inline-block" role="button" aria-haspopup="dialog" aria-label="Open cart">
              <div class="w-inline-block">Cart (</div>
              <div class="w-commerce-commercecartopenlinkcount cart-quantity">0</div>
              <div class="w-inline-block">)</div>
            </a> {% endcomment %}
            {% comment %} <div data-node-type="commerce-cart-container-wrapper" style="display:none" class="w-commerce-commercecartcontainerwrapper w-commerce-commercecartcontainerwrapper--cartType-modal">
              <div data-node-type="commerce-cart-container" role="dialog" class="w-commerce-commercecartcontainer cart-container">
                <div class="w-commerce-commercecartheader">
                  <h4 class="w-commerce-commercecartheading">Your Cart</h4>
                  <a href="#" data-node-type="commerce-cart-close-link" class="w-commerce-commercecartcloselink w-inline-block" role="button" aria-label="Close cart"><svg width="16px" height="16px" viewbox="0 0 16 16">
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g fill-rule="nonzero" fill="#333333">
                          <polygon points="6.23223305 8 0.616116524 13.6161165 2.38388348 15.3838835 8 9.76776695 13.6161165 15.3838835 15.3838835 13.6161165 9.76776695 8 15.3838835 2.38388348 13.6161165 0.616116524 8 6.23223305 2.38388348 0.616116524 0.616116524 2.38388348 6.23223305 8"></polygon>
                        </g>
                      </g>
                    </svg></a>
                </div>
                <div class="w-commerce-commercecartformwrapper">
                  <form data-node-type="commerce-cart-form" style="display:none" class="w-commerce-commercecartform default-state">
                    <script type="text/x-wf-template" id="wf-template-3b64cdfd-cf2d-cf2e-2ac0-f96e95e61106"></script>
                    <div class="w-commerce-commercecartlist cart-list" data-wf-collection="database.commerceOrder.userItems" data-wf-template-id="wf-template-3b64cdfd-cf2d-cf2e-2ac0-f96e95e61106"></div>
                    <div class="w-commerce-commercecartfooter">
                      <div aria-live="" aria-atomic="false" class="w-commerce-commercecartlineitem">
                        <div>Subtotal</div>
                        <div class="w-commerce-commercecartordervalue text-bold"></div>
                      </div>
                      <div>
                        <div data-node-type="commerce-cart-quick-checkout-actions">
                          <a role="button" tabindex="0" aria-label="Apple Pay" aria-haspopup="dialog" data-node-type="commerce-cart-apple-pay-button" style="background-image:-webkit-named-image(apple-pay-logo-white);background-size:100% 50%;background-position:50% 50%;background-repeat:no-repeat" class="w-commerce-commercecartapplepaybutton apple-pay-btn cart">
                            <div></div>
                          </a>
                          <a role="button" tabindex="0" aria-haspopup="dialog" data-node-type="commerce-cart-quick-checkout-button" style="display:none" class="w-commerce-commercecartquickcheckoutbutton"><svg class="w-commerce-commercequickcheckoutgoogleicon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" viewbox="0 0 16 16">
                              <defs>
                                <polygon id="google-mark-a" points="0 .329 3.494 .329 3.494 7.649 0 7.649"></polygon>
                                <polygon id="google-mark-c" points=".894 0 13.169 0 13.169 6.443 .894 6.443"></polygon>
                              </defs>
                              <g fill="none" fill-rule="evenodd">
                                <path fill="#4285F4" d="M10.5967,12.0469 L10.5967,14.0649 L13.1167,14.0649 C14.6047,12.6759 15.4577,10.6209 15.4577,8.1779 C15.4577,7.6339 15.4137,7.0889 15.3257,6.5559 L7.8887,6.5559 L7.8887,9.6329 L12.1507,9.6329 C11.9767,10.6119 11.4147,11.4899 10.5967,12.0469"></path>
                                <path fill="#34A853" d="M7.8887,16 C10.0137,16 11.8107,15.289 13.1147,14.067 C13.1147,14.066 13.1157,14.065 13.1167,14.064 L10.5967,12.047 C10.5877,12.053 10.5807,12.061 10.5727,12.067 C9.8607,12.556 8.9507,12.833 7.8887,12.833 C5.8577,12.833 4.1387,11.457 3.4937,9.605 L0.8747,9.605 L0.8747,11.648 C2.2197,14.319 4.9287,16 7.8887,16"></path>
                                <g transform="translate(0 4)">
                                  <mask id="google-mark-b" fill="#fff">
                                    <use xlink:href="#google-mark-a"></use>
                                  </mask>
                                  <path fill="#FBBC04" d="M3.4639,5.5337 C3.1369,4.5477 3.1359,3.4727 3.4609,2.4757 L3.4639,2.4777 C3.4679,2.4657 3.4749,2.4547 3.4789,2.4427 L3.4939,0.3287 L0.8939,0.3287 C0.8799,0.3577 0.8599,0.3827 0.8459,0.4117 C-0.2821,2.6667 -0.2821,5.3337 0.8459,7.5887 L0.8459,7.5997 C0.8549,7.6167 0.8659,7.6317 0.8749,7.6487 L3.4939,5.6057 C3.4849,5.5807 3.4729,5.5587 3.4639,5.5337" mask="url(#google-mark-b)"></path>
                                </g>
                                <mask id="google-mark-d" fill="#fff">
                                  <use xlink:href="#google-mark-c"></use>
                                </mask>
                                <path fill="#EA4335" d="M0.894,4.3291 L3.478,6.4431 C4.113,4.5611 5.843,3.1671 7.889,3.1671 C9.018,3.1451 10.102,3.5781 10.912,4.3671 L13.169,2.0781 C11.733,0.7231 9.85,-0.0219 7.889,0.0001 C4.941,0.0001 2.245,1.6791 0.894,4.3291" mask="url(#google-mark-d)"></path>
                              </g>
                            </svg><svg class="w-commerce-commercequickcheckoutmicrosofticon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16">
                              <g fill="none" fill-rule="evenodd">
                                <polygon fill="#F05022" points="7 7 1 7 1 1 7 1"></polygon>
                                <polygon fill="#7DB902" points="15 7 9 7 9 1 15 1"></polygon>
                                <polygon fill="#00A4EE" points="7 15 1 15 1 9 7 9"></polygon>
                                <polygon fill="#FFB700" points="15 15 9 15 9 9 15 9"></polygon>
                              </g>
                            </svg>
                            <div>Pay with browser.</div>
                          </a>
                        </div>
                        <a href="checkout.html" value="Continue to Checkout" data-node-type="cart-checkout-button" class="w-commerce-commercecartcheckoutbutton btn-primary" data-loading-text="Hang Tight...">Continue to Checkout</a>
                      </div>
                    </div>
                  </form>
                  <div class="w-commerce-commercecartemptystate empty-state-cart">
                    <div class="heading-h4-size mg-bottom-16px">No items found.</div>
                    <a href="subscribe.html" class="btn-primary w-button">Subscribe now!</a>
                  </div>
                  <div aria-live="" style="display:none" data-node-type="commerce-cart-error" class="w-commerce-commercecarterrorstate error-message cart">
                    <div class="w-cart-error-msg" data-w-cart-quantity-error="Product is not available in this quantity." data-w-cart-general-error="Something went wrong when adding this item to the cart." data-w-cart-checkout-error="Checkout is disabled on this site." data-w-cart-cart_order_min-error="The order minimum was not met. Add more items to your cart to continue." data-w-cart-subscription_error-error="Before you purchase, please use your email invite to verify your address so we can send order updates.">Product is not available in this quantity.</div>
                  </div>
                </div>
              </div>
            </div> {% endcomment %}
          </div>
          <div>
            <div data-hover="true" data-delay="0" data-w-id="605b4ac3-f9a6-4bb8-3302-9607726014bf" class="dropdown-wrapper user w-dropdown">
              <div class="dropdown-toggle w-dropdown-toggle">
                <div class="line-rounded-icon dropdown"></div>
                <div class="line-rounded-icon dropdown-arrow user"></div>
              </div>
              <nav class="dropdown-column-wrapper small no-static w-dropdown-list">
                <div class="dropdown-pd small extra">
                  <div class="w-layout-grid grid-1-column dropdown-link-column single">
                    {% if request.user.is_authenticated %}
                      <a href="{% url 'posts:profile' request.user %}" class="dropdown-link w-dropdown-link">Account</a>
                      <a href="{% url 'users:password_change' %}" class="dropdown-link w-dropdown-link">Settings</a>
                      <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="log-link" type="submit">Log Out</button>
                      </form>
                    {% else %}
                      <a href="{% url 'users:login' %}" class="dropdown-link w-dropdown-link">Log In</a>
                      <a href="{% url 'users:signup' %}" class="dropdown-link w-dropdown-link">Sign Up</a>
                    {% endif %}
                  </div>
                </div>
              </nav>
            </div>
          </div>
          <a data-w-id="b9a9b5c1-043b-4101-f32c-1193bfae0b9c" href="#" class="btn-circle-primary no-bg search w-inline-block">
            <div class="line-rounded-icon"></div>
          </a>
        </div>
      </div>
      <div class="header-middle">
        <div class="hamburger-menu-wrapper w-nav-button">
          <div class="hamburger-menu-bar top"></div>
          <div class="hamburger-menu-bar bottom"></div>
        </div>
        <nav role="navigation" class="header-nav-menu-wrapper middle w-nav-menu">
          <ul role="list" class="header-nav-menu-list middle">
            <li class="header-nav-list-item middle">
              <a href="{% url 'homepage:index' %}" aria-current="page" class="header-nav-link w-nav-link w--current">Home</a>
            </li>
            <li class="header-nav-list-item middle">
              <div data-hover="true" data-delay="0" data-w-id="be26c77c-d817-70bc-a38d-79cfaf77f00f" class="dropdown-wrapper w-dropdown">
                <div class="dropdown-toggle w-dropdown-toggle">
                  <div>Categories</div>
                  <div class="line-rounded-icon dropdown-arrow"></div>
                </div>
                <nav class="dropdown-column-wrapper small w-dropdown-list">
                  <div class="dropdown-pd small">
                    <div class="w-dyn-list">
                      <div role="list" class="grid-1-column dropdown-link-column w-dyn-items">
                        {% for group in group_list %}
                        <div role="listitem" class="w-dyn-item">
                          <a href="{% url 'posts:group' group.slug %}" class="dropdown-link w-dropdown-link">{{group.title}}</a>
                        </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </nav>
              </div>
            </li>
            <li class="header-nav-list-item middle">
              <a href="{% url 'contacts:contact' %}" class="header-nav-link w-nav-link">Contact</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="header-nav-list-item middle">
              <a href="{% url 'posts:create' %}" class="header-nav-link w-nav-link"><strong>Create</strong></a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="search-modal">
    <div class="card modal">
        <div class="text-center">
          <h3 class="mg-bottom-24px">Search for articles</h3>
        </div>
        {% include "includes/search_input.html" %}
      <div data-w-id="38b0f4f3-a5b2-8a3b-0caf-84f4fcd524c2" class="modal-close">
        <div class="line-rounded-icon modal"></div>
      </div>
    </div>
  </div>
</div>